DROP TABLE IF EXISTS urls;

CREATE TABLE urls (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    hash_id TEXT,
    original_url TEXT NOT NULL,
    clicks INTEGER NOT NULL DEFAULT 0
);

